name: Run Jama API Script

on:
  push:
    branches:
      - main  # Change this to the branch you want to trigger the action on

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3  # Updated to v3

      - name: Set up Python
        uses: actions/setup-python@v4  # No change needed; it's still v4

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas py-jama-rest-client xlsxwriter

      - name: Set environment variables
        run: |
          echo "JAMA_CLIENT_ID=${{ secrets.JAMA_CLIENT_ID }}" >> $GITHUB_ENV
          echo "JAMA_CLIENT_SECRET=${{ secrets.JAMA_CLIENT_SECRET }}" >> $GITHUB_ENV

      - name: Run the script
        run: |
          python kpi.py  # Replace with the name of your Python script
