name: Run Jama API Script

on:
  push:
    branches:
      - main  # Change this to the branch you want to trigger the action on

permissions:
  contents: write  # Allow the workflow to push changes to the repository

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # Updated to v4

      - name: Set up Python
        uses: actions/setup-python@v4  # This stays as v4
        with:
          python-version: '3.12'  # Specify the desired Python version here
        env:  # Force Node 20 for JavaScript actions
          FORCE_JAVASCRIPT_ACTIONS_TO_NODE20: true

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas py-jama-rest-client

      - name: Set environment variables
        run: |
          echo "JAMA_CLIENT_ID=${{ secrets.JAMA_CLIENT_ID }}" >> $GITHUB_ENV
          echo "JAMA_CLIENT_SECRET=${{ secrets.JAMA_CLIENT_SECRET }}" >> $GITHUB_ENV

      - name: Run the script
        run: |
          python kpi.py  # Replace with the name of your Python script

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions"  # Set a username for the commit
          git config --global user.email "github-actions@github.com"  # Set an email for the commit
          git add kp_data.csv defect_data.csv testrun_data.csv  # Add the generated CSV files to the commit
          git commit -m "Update KPI and defect data CSV files" || echo "No changes to commit"  # Commit the changes
          git push  # Push the changes to the main branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # GitHub token for authentication
